# Generated by Django 5.1.7 on 2025-03-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaveadjustment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaveadjustment',
            name='leave_request',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='systemized_by',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='LeaveAdjustment',
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
