# Generated by Django 5.1.7 on 2025-03-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='entering_type',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manual_total_days',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
