# Generated by Django 5.1.7 on 2025-05-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_teacard_holder',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
