# Generated by Django 5.1.7 on 2025-06-06 09:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_is_teacard_holder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, help_text='Seniority level. Lower = higher rank (e.g., 1 = Dean)', null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
