# Generated by Django 5.1.7 on 2025-04-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
