# Generated by Django 5.1.7 on 2025-03-18 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_leave_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='end_date',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='coming_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='leave_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=21, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10),
        ),
    ]
