# Generated by Django 5.1.7 on 2025-06-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_employee_position_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
