# Generated by Django 5.1.7 on 2025-06-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_title_remove_designation_level_designation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='coverable_late_count',
            field=models.IntegerField(blank=True, default=3, help_text='Number of coverable late arrivals allowed per month', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='late_count',
            field=models.IntegerField(blank=True, default=5, help_text='Number of late arrivals allowed per month', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='short_leave_count',
            field=models.IntegerField(blank=True, default=2, help_text='Number of short leaves allowed per month', null=True),
        ),
    ]
