# Generated by Django 5.1.7 on 2025-03-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_leave_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
