# Generated by Django 5.1.7 on 2025-03-20 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_leavetype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLeaveSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('request_type', models.CharField(choices=[('half', 'Half Day'), ('full', 'Full Day')], max_length=10)),
                ('total_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'unique_together': {('employee', 'year', 'month', 'request_type')},
            },
        ),
    ]
