# Generated by Django 5.1.7 on 2025-06-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_title_coverable_late_count_title_late_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='title_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
