# Generated by Django 5.1.7 on 2025-03-20 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_monthlyleavesummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyleavesummary',
            name='id',
        ),
        migrations.AddField(
            model_name='monthlyleavesummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyleavesummary',
            name='uid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyleavesummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
