# Generated by Django 5.1.7 on 2025-03-24 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_monthlyleavesummary_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyleavesummary',
            unique_together={('employee', 'year', 'month')},
        ),
        migrations.AlterField(
            model_name='monthlyleavesummary',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='monthlyleavesummary',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyleavesummary',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='monthlyleavesummary',
            name='request_type',
        ),
    ]
