# Generated by Django 5.1.7 on 2025-03-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_monthlyleavesummary_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyleavesummary',
            name='total_days',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
