# Generated by Django 5.1.7 on 2025-03-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_leaverequest_total_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='total_days',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=5, null=True),
        ),
    ]
