# Generated by Django 5.1.7 on 2025-03-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_alter_leaverequest_total_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='leave_balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='total_days',
            field=models.FloatField(blank=True, default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='monthlyleavesummary',
            name='total_days',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
