# Generated by Django 5.1.7 on 2025-03-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_leavetype_max_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyleavesummary',
            name='total_days',
            field=models.FloatField(default=0.0),
        ),
    ]
