# Generated by Django 5.1.7 on 2025-03-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_alter_monthlyleavesummary_total_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyleavesummary',
            name='total_days',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
