# Generated by Django 5.1.7 on 2025-04-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryUserPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_user.png', null=True, upload_to='profile_images/'),
        ),
    ]
