# Generated by Django 5.1.7 on 2025-04-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username_alt_uid',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
