# Generated by Django 5.1.7 on 2025-03-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
