# Generated by Django 5.1.7 on 2025-03-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_alter_faculty_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
